statements ::= lineOfCode restofStatements

restofStatements ::= <CR> lineOfCode restofStatements
restofStatements ::=

lineOfCode ::= <NUMBER> statement
lineOfCode ::=

statement ::= <PRINT> expression
statement ::= <GOTO> expression
statement ::= <GOSUB> expression
statement ::= <RETURN>
statement ::= <INPUT> list
statement ::= <LET> <IDENTIFIER> <EQ> expression
statement ::= <IF> expression reloop expression <THEN> statement elseStatement
statement ::= <GOTO> expression
statement ::= <END>
statement ::= <REM> <STRING>

elseStatement ::= <ELSE> statements
elseStatement ::=

expression ::= factor <*> factor
expression ::= factor </> factor
expression ::= factor <+> factor
expression ::= factor <-> factor
expression ::= factor

list ::= <IDENTIFIER> array restofList

restofList ::= <COMA> <IDENTIFIER> array restofList
restofList ::=

array ::= <OPEN_PARENT> expression <CLOSE_PARENT>
array ::=

factor ::= <NUMBER>
factor ::= <IDENTIFIER>

reloop ::= <EQ>
reloop ::= <DIFF>
reloop ::= <LT>
reloop ::= <GT>
reloop ::= <LE>
reloop ::= <GE>