/* Generated By:JavaCC: Do not edit this line. BasicParserConstants.java */
package fr.utbm.info.da53.lw2.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface BasicParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CR = 5;
  /** RegularExpression Id. */
  int PRINT = 6;
  /** RegularExpression Id. */
  int EQ = 7;
  /** RegularExpression Id. */
  int ADD = 8;
  /** RegularExpression Id. */
  int MUL = 9;
  /** RegularExpression Id. */
  int STRING = 10;
  /** RegularExpression Id. */
  int NUMBER = 11;
  /** RegularExpression Id. */
  int ID = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "<token of kind 4>",
    "\"\\n\"",
    "\"print\"",
    "\"=\"",
    "<ADD>",
    "<MUL>",
    "<STRING>",
    "<NUMBER>",
    "<ID>",
    "\"(\"",
    "\")\"",
  };

}
